package com.jc.jdbcpoc;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;

import com.jc.jdbcpoc.utils.JDBCConstants;

public class AutoIncrment {
	public static void main(String[] args) {
		try {
			findById();
			String sql = "insert into users (sname,email,pwd) values (?,?,?)";
			Connection con = DriverManager.getConnection(JDBCConstants.DB_URL, JDBCConstants.USR_NAME,
					JDBCConstants.PWD);
			PreparedStatement ps = con.prepareStatement(sql, PreparedStatement.RETURN_GENERATED_KEYS);
			ps.setString(1, "chaitu");
			ps.setString(2, "cha@gmail.com");
			ps.setString(3, "123456789");
			int executeUpdate = ps.executeUpdate();
			if (executeUpdate > 0) {
				ResultSet res = ps.getGeneratedKeys();
				System.out.println(
						"Auto-incremented values of the column ID generated by the current PreparedStatement object: ");
				while (res.next()) {
					System.out.println(res.getString(1));
				}
			}
		} catch (Exception e) {
			System.out.println(e.getMessage());
		}
	}

	public static void findById() {
		try {
			String sql = "select * from users where id=?";
			Connection con = DriverManager.getConnection(JDBCConstants.DB_URL, JDBCConstants.USR_NAME,
					JDBCConstants.PWD);
			checkIfDbExists(con, "users");
			PreparedStatement ps = con.prepareStatement(sql);
			ps.setInt(1, 1);
			ResultSet rs = ps.executeQuery();
			List<String> ls = new ArrayList<String>();
			while (rs.next()) {
				ls.add(rs.getString(2));
				ls.add(rs.getString(3));
			}
			if (ls.isEmpty()) {
				System.out.println("Record not found");
			} else {
				System.out.println(ls);
			}

		} catch (Exception e) {
			System.out.println(e.getMessage());
		}
	}

	public static boolean checkIfDbExists(Connection conn, String dbName) throws SQLException {
		ResultSet resultSet = conn.getMetaData().getTables(null, null, dbName, null);

		// iterate each catalog in the ResultSet
		while (resultSet.next()) {
			String databaseName = resultSet.getString("TABLE_NAME");
			System.out.println(databaseName);
			if (dbName.equalsIgnoreCase(databaseName)) {
				return true;
			}
		}
		resultSet.close();
		return false;
	}
}
